# Generated by Django 2.1.3 on 2019-01-11 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transaction',
            new_name='traninfo',
        ),
    ]
